version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_db_ucrud
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data-ucrud:/var/lib/postgresql/data
      - ./db/initi:/docker-entrypoint-initdb.d
    restart: always

volumes:
  postgres-data-ucrud:
    driver: local
